apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nginx
  labels:
    tier: backend
spec:  
  replicas: 3
  selector:  
    matchLabels: 
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.23.0
          ports:
          - containerPort: 80


# apiVersion: apps/v1
# kind: Deployment
# metadata:  
#   name: nginx
#   labels:
#     tier: backend
# spec:  
#   template:
#     metadata:
#       name:
#       labels:
#         tier: backend
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:1.23.0
#           ports:
#           - containerPort: 80
#   replicas:  3
#   selector:  
#     matchLabels: 
#       tier: backend
